#include "subprojects\std_lib_facilities\std_lib_facilities.h"
#include "subprojects/animationwindow/include/AnimationWindow.h"
#include "oppgave1.h"
#include "oppgave2.h"
#include "oppgave3.h"
#include "oppgave4.h"
#include "oppgave5.h"
#include <cstdlib>  
#include <ctime>    